language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install: travis_wait 30 mvn install
  - pip install -r requirements.txt
  - pip install coverage pytest

script:
  - coverage run -m pytest
  - black --check ./

after_success:
  - bash <(curl -s https://codecov.io/bash)
